language: python

matrix:
  include:
    - python: 2.7
      dist: trusty
    - python: 3.4
      dist: trusty
    - python: 3.5
      dist: trusty
    - python: 3.6
      dist: trusty
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: bionic
    - python: 3.9
      dist: bionic
    - python: 3.10
      dist: bionic

install:
  - pip install .
  - pip install pytest

script:
  - py.test
